trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'copa-filmes-front'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install sonarqube-scanner --save-dev
    sonar.projectKey=luancarloswd_copa-filmes-front \
    sonar.organization=luancarloswd-github \
    sonar.sources=. \
    sonar.host.url=https://sonarcloud.io \
    sonar.login=$(sonarId)
    npm install
    ng build --prod
    docker build -f Dockerfile -t $(dockerId)/$(imageName):latest -t $(dockerId)/$(imageName):$(Build.BuildId) .
    npm run sonar
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName):$(Build.BuildId)
    docker push $(dockerId)/$(imageName):latest
  env:
    pswd: $(dockerPassword)
  displayName: 'npm install and build'